# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SynKsiendza's Main Page
description: This is the page for all my coding related work!
baseurl: / # the subpath of your site, e.g. /support
url: https://synksiendza.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Portfolio And Projects #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Kacper Trzosiński
header: Here is my world!

meta_image: odin-meta.png

# Social Links
github_username: SynKsiendza
email: kacpertrzosinski@proton.me


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/TeaGuns/odin

nav_item_two: Projects
nav_item_two_link: ./projects

nav_button: Return to Home
nav_button_link: https://synksiendza.github.io/

# More Help
help_one_title: My Github
help_one_content: To find more of my projects navigate to my GitHub
help_one_button: Github
help_one_link: https://github.com/SynKsiendza

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
